# Dockerfile.old
FROM python:3.8-slim

WORKDIR /app
COPY old/ /app/

RUN pip install --upgrade pip \
    && pip install pip-audit safety \
    && pip install -r requirements.txt

CMD ["python", "app.py"]
